a = try: b() catch err: false
