try:
  try {
    1
  }
catch err:
  2
finally:
  3
