try f() catch err: err
