f() -/>
  x = try: await g() catch err: err
