try {
  1
} catch err:
  2
