try: a catch err: panic()
